[package]
name = "unmixing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gdal = "0.11.0"
csv = "1.1.6"
structopt = "0.3.25"
rand = "0.8.4"
indicatif = {version = "*", features = ["rayon"]}
rayon = "1.5.1"
nalgebra = "0.29.0"
argmin = { version = "0.4.7", features = ["nalgebral"] }
finitediff = "0.1.4"